# Generated by Django 4.2.4 on 2023-08-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
