# Generated by Django 4.2.4 on 2023-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm_app', '0002_posts_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_public',
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
